#!/bin/bash
set -e

# Start AWS services to enable production
# 1. Update ASG
# 2. Enable CloudFront

# Import env
source ./.env.bin.local

asg_desired_capacity=1
asg_min_size=0
asg_max_size=2
ecs_task_count=2

# Update ASG size
echo "Updating Auto Scaling Group $ASG (desired_capacity: $asg_desired_capacity, min_size: $asg_min_size, max_size: $asg_max_size)"
aws autoscaling update-auto-scaling-group \
  --profile $AWS_PROFILE \
  --auto-scaling-group-name $ASG \
  --desired-capacity $asg_desired_capacity \
  --min-size $asg_min_size \
  --max-size $asg_max_size
  
# Update ECS Service desired tasks count
echo "Updating ECS service desired task count to $ecs_task_count"
aws ecs update-service \
  --profile $AWS_PROFILE \
  --cluster $ECS_CLUSTER \
  --service $ECS_SERVICE \
  --desired-count $ecs_task_count \
  > /dev/null

# Enable CloudFront
distribution=$(
  aws cloudfront get-distribution \
    --profile $AWS_PROFILE \
    --id $CLOUDFRONT_DISTRIBUTION
)

distribution_config=$(echo "$distribution" | jq '.Distribution.DistributionConfig')

is_distribution_config_enabled=$(echo "$distribution_config" | jq '.Enabled')

if [[ $is_distribution_config_enabled = false ]]; then
  echo "Enabling CloudFront distribution $CLOUDFRONT_DISTRIBUTION"

  distribution_etag=$(echo "$distribution" | jq -r '.ETag')

  enabled_distribution_config=$(
    echo "$distribution_config" | jq '.Enabled = true'
  )

  aws cloudfront update-distribution \
    --profile $AWS_PROFILE \
    --id $CLOUDFRONT_DISTRIBUTION \
    --if-match $distribution_etag \
    --distribution-config "$enabled_distribution_config" \
    > /dev/null
    
else
  echo "CloudFront distribution $CLOUDFRONT_DISTRIBUTION is already enabled"
fi